1718/bnd maven plugin
Adobe-Consulting-Services/acs-aem-commons pull request #2423
Opened 2020-09-28 13:38 UTC by davidjgonzalez

Update project to use bnd-maven-plugin

2020-09-28 13:40 UTC, davidjgonzalez commented
@adamcin when verifying my build, oakpal is complaining: 

```
[ERROR] Failed to execute goal net.adamcin.oakpal:oakpal-maven-plugin:2.1.0:scan (oakpal-scan) on project acs-aem-commons-ui.apps: Failed to execute package scan. Failed to resolve cndNames.: Failed to find node type definition on classpath for cndName nodetypes/nodetypes.cnd -> [Help 1]
```

however the node this path exists (no changes to it from master) .. `<project root>/src/test/resources/nodetypes/nodetypes.cnd `

Any idea why? I'm guessing its something simple I'm overlooking... 🤦

2020-09-28 13:41 UTC, davidjgonzalez commented
@kwin / @joerghoh - if you get a moment cant you take a quick pre-review look at this? Your maven-foo is stronger than mine and want to make sure I didn't botch syntax (esp in CDATA) and/or there isn't a more efficient configuration.

2020-09-28 13:50 UTC, kwin requested changes

2020-09-28 13:50 UTC, kwin commented on bundle/pom.xml
> +Bundle-DocURL:
I would move the -exportcontents, -snapshot and Bundle-DocURL instructions/headers to the parent pom's bnd configuration (it is not specific to this bundle)

2020-09-28 13:50 UTC, kwin commented on bundle/pom.xml
> +-snapshot: ${tstamp;yyyyMMddHHmmssSSS}
Probably we can stay with SNAPSHOT as recommended in https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#reproducible-builds.

2020-09-28 13:50 UTC, kwin commented on bundle/pom.xml
> +-plugin org.apache.sling.bnd.models.ModelsScannerPlugin
we still need to Felix SCR plugin as long as we are not yet on the OSGi annotations

2020-09-28 13:50 UTC, kwin commented on bundle/pom.xml
> +Bundle-DocURL:
The Bundle-DocUrl should point to the Github site.

2020-09-28 13:50 UTC, kwin commented on pom.xml
>                  <!-- all custom plugins -->
maven-scr-plugin needs to be removed (it is not compatible with bnd-maven-plugin)

2020-09-28 13:50 UTC, kwin commented on pom.xml
>                  <!-- all custom plugins -->
remove  maven-bundle-plugin!

2020-09-29 19:56 UTC, adamcin commented
> @adamcin when verifying my build, oakpal is complaining:
> 
> ```
> [ERROR] Failed to execute goal net.adamcin.oakpal:oakpal-maven-plugin:2.1.0:scan (oakpal-scan) on project acs-aem-commons-ui.apps: Failed to execute package scan. Failed to resolve cndNames.: Failed to find node type definition on classpath for cndName nodetypes/nodetypes.cnd -> [Help 1]
> ```
> 
> however the node this path exists (no changes to it from master) .. `<project root>/src/test/resources/nodetypes/nodetypes.cnd `
> 
> Any idea why? I'm guessing its something simple I'm overlooking... 🤦

@davidjgonzalez Can you confirm that the cnd is being copied to `target/test-classes/nodetypes/nodetypes.cnd`?

2020-10-30 20:31 UTC, davidjgonzalez commented
@adamcin I do not see these `target/test-classes/nodetypes/nodetypes.cnd` in my `ui.apps` project.

I actually tried doing an `mvn clean install` from master and ran into the same issue.

2020-10-30 21:06 UTC, davidjgonzalez commented
@adamcin so this is strange (and maybe why i haven't seen this before). Everything seems to work in intellij, however when i run the command from the command line it fails.
My version of maven is the same 3.6.3 (command line is 3.6.3_1), and I'm using the same version of java. That help ring any bells?

2020-11-03 14:33 UTC, davidjgonzalez commented
Closing for now. To pick up post 5.0

2020-11-03 14:33 UTC, closed without merging