Update to the latest sling-maven-plugin
Adobe-Consulting-Services/acs-aem-commons pull request #2428
Opened 2020-10-09 15:53 UTC by royteeuwen

Update to the latest sling-maven-plugin and enable SlingPostServlet install which also installs the intermediate folders and doesnt fail the install when they dont exist

2020-10-11 15:27 UTC, joerghoh requested changes

2020-10-11 15:27 UTC, joerghoh commented on bundle/pom.xml
> +                <artifactId>sling-maven-plugin</artifactId>
This whole configuration breaks our travis build

2020-10-12 06:31 UTC, royteeuwen commented
@joerghoh fixed now!

2020-10-13 16:02 UTC, davidjgonzalez approved these changes

2020-10-13 16:02 UTC, merged