Update AEM dependencies to 6.5.10
Adobe-Consulting-Services/acs-aem-commons pull request #3081
Opened 2023-04-02 15:30 UTC by kwin

2023-04-02 17:41 UTC, kwin commented
Testing with JDK17 still fails for some reason....

2023-04-21 13:03 UTC, davidjgonzalez requested changes
GActions are failing

2023-04-21 13:11 UTC, kwin commented
> GActions are failing

Yes, I know, compare with https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3081#issuecomment-1493399882. Any pointers appreciated.

2023-05-16 18:54 UTC, kwin commented
@stefanseifert Any chance you have an idea why the `RemoteAssetDecoratorTest` fails with newer dependencies? It seems that the `RemoteAssetDecorator` being registered in `RemoteAssetDecoratorTest.setupFinish()` is never bound as `ResourceDecorator` in https://github.com/apache/sling-org-apache-sling-resourceresolver/blob/46f67c7cff13071d96cf58dde86730b6ffbb2639/src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverFactoryActivator.java#L609....

2023-05-17 18:13 UTC, davidjgonzalez commented on pom.xml
> -                        <failOnError>false</failOnError>
hmmm - i do not recall :(

2023-06-10 10:48 UTC, kwin commented
@davidjgonzalez Anything outstanding here?

2023-06-10 12:00 UTC, merged

2023-06-10 12:00 UTC, davidjgonzalez commented
Nope! I must have missed it on last release! Merged